err
Command line: /Users/a1667917/mambaforge/envs/dnaaplertest/bin/python3.8 /Users/a1667917/Documents/dnaapler/tests/helpers/run_test.py output input
